CREATE TABLE TAIKHOAN(
    TENTAIKHOAN     VARCHAR2(20) NOT NULL,
    MATKHAU         VARCHAR(30) NOT NULL,
    
    CONSTRAINT P_TAIKHOAN PRIMARY KEY (TENTAIKHOAN)
);

CREATE TABLE QUYEN(
    MAQUYEN         VARCHAR2(10) NOT NULL,
    QUYEN           VARCHAR2(20) NOT NULL,
    
    CONSTRAINT P_QUYEN PRIMARY KEY (MAQUYEN)
);

CREATE TABLE PHANQUYENTAIKHOAN(
    TENTAIKHOAN     VARCHAR2(20) NOT NULL,
    MAQUYEN         VARCHAR2(10) NOT NULL,
    
    CONSTRAINT P_PHANQUYENTAIKHOAN PRIMARY KEY (TENTAIKHOAN, MAQUYEN),
    CONSTRAINT F_PQTK_TK FOREIGN KEY (TENTAIKHOAN) REFERENCES TAIKHOAN(TENTAIKHOAN),
    CONSTRAINT F_PQTK_Q FOREIGN KEY (MAQUYEN) REFERENCES QUYEN(MAQUYEN)
);

CREATE TABLE CHUYENKHOA(
    MACHUYENKHOA    VARCHAR2(10) NOT NULL,
    TENCHUYENKHOA   NVARCHAR2(30),
    
    CONSTRAINT P_CHUYENKHOA PRIMARY KEY (MACHUYENKHOA)
);

CREATE TABLE BACSI(
    MABACSI         VARCHAR2(10) NOT NULL,
    HOTEN   		NVARCHAR2(30),
	GIOITINH		NVARCHAR2(3),
    HOCHAM          NVARCHAR2(30),
    ANHDAIDIEN      BLOB,
    GIOITHIEU       CLOB,
    MACHUYENKHOA    VARCHAR2(10),
    TRANGTHAI       NVARCHAR2(20),
    NGAYCAPNHAT     DATE,
    TAIKHOAN        VARCHAR2(20),
    
    CONSTRAINT P_BACSI PRIMARY KEY (MABACSI),
    CONSTRAINT F_BS_CK FOREIGN KEY (MACHUYENKHOA) REFERENCES CHUYENKHOA(MACHUYENKHOA),
    CONSTRAINT F_BS_TK FOREIGN KEY (TAIKHOAN) REFERENCES TAIKHOAN(TENTAIKHOAN)
);

CREATE TABLE HOCVI(
    MAHOCVI         VARCHAR2(10) NOT NULL,
    TENHOCVI        NVARCHAR2(30),
    BACHOCVI        NUMBER,
    
    CONSTRAINT P_HOCVI PRIMARY KEY (MAHOCVI)
);

CREATE TABLE HOCVIBACSI(
    MABACSI         VARCHAR2(10) NOT NULL,
    MAHOCVI         VARCHAR2(10) NOT NULL,
    
    CONSTRAINT P_HV_BS PRIMARY KEY (MABACSI, MAHOCVI),
    CONSTRAINT F_BVBS_BS FOREIGN KEY (MABACSI) REFERENCES BACSI(MABACSI),
    CONSTRAINT F_BVBS_HV FOREIGN KEY (MAHOCVI) REFERENCES HOCVI(MAHOCVI)
);

CREATE TABLE PHONG(
    MAPHONG         VARCHAR2(10) NOT NULL,
    TENPHONG        NVARCHAR2(30),
    VITRI           NVARCHAR2(30),
    
    CONSTRAINT P_PHONG PRIMARY KEY (MAPHONG)
);

CREATE TABLE LICHLAMVIEC(
    MALICH          VARCHAR2(10) NOT NULL,
    MABACSI         VARCHAR2(10) NOT NULL,
    MAPHONG         VARCHAR2(10) NOT NULL,
    NGAYLAM         DATE NOT NULL,
    
    CONSTRAINT P_LLV PRIMARY KEY (MALICH),
    CONSTRAINT F_LLV_BS FOREIGN KEY (MABACSI) REFERENCES BACSI(MABACSI),
    CONSTRAINT F_LLV_P FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG)
);

CREATE TABLE BENHNHAN(
    MABENHNHAN      VARCHAR2(10) NOT NULL,
    HOTEN   		NVARCHAR2(30),
	GIOITINH		NVARCHAR2(3),
    DIACHI          NVARCHAR2(100),
    NAMSINH         NUMBER,
    TAIKHOAN        VARCHAR2(20),
    DIENTHOAI       VARCHAR2(10),
    
    CONSTRAINT P_BENHNHAN PRIMARY KEY (MABENHNHAN),
    CONSTRAINT F_BN_TK FOREIGN KEY (TAIKHOAN) REFERENCES TAIKHOAN(TENTAIKHOAN)
);


CREATE TABLE NHANVIEN(
    MANHANVIEN      VARCHAR2(10) NOT NULL,
    HOTEN           NVARCHAR2(30),
    BOPHAN          NVARCHAR2(30),
    TAIKHOAN        VARCHAR2(20),
    
    CONSTRAINT P_NHANVIEN PRIMARY KEY (MANHANVIEN),
    CONSTRAINT F_NV_TK FOREIGN KEY (TAIKHOAN) REFERENCES TAIKHOAN(TENTAIKHOAN)
);

CREATE TABLE PHIEUDANGKY(
    MAPHIEUDANGKY       VARCHAR2(10) NOT NULL,
    NGAYLAP             DATE,
    MABHYT              VARCHAR2(20),
    TRANGTHAITHANHTOAN  NVARCHAR2(20),
    MABENHNHAN          VARCHAR2(10),
    NVLAP               VARCHAR2(10),
    NVTHANHTOAN         VARCHAR2(10),
    LICHLAMVIEC         VARCHAR2(10),
    TINHTRANGSUCKHOE    NVARCHAR2(100),
    STTTIEPNHAN         NUMBER,

    CONSTRAINT P_PHIEUDANGKY PRIMARY KEY (MAPHIEUDANGKY),
    CONSTRAINT F_PDK_BN FOREIGN KEY (MABENHNHAN) REFERENCES BENHNHAN(MABENHNHAN),
    CONSTRAINT F_PDK_L FOREIGN KEY (LICHLAMVIEC) REFERENCES LICHLAMVIEC(MALICH),
    CONSTRAINT F_PDK_NV FOREIGN KEY (NVLAP) REFERENCES NHANVIEN(MANHANVIEN),
    CONSTRAINT F_PDK_NVTT FOREIGN KEY (NVTHANHTOAN) REFERENCES NHANVIEN(MANHANVIEN)
);



CREATE TABLE PHIEUKHAM(
    MAPHIEUKHAM         VARCHAR2(10) NOT NULL,
    MAPHIEUDANGKY       VARCHAR2(10),
    NGAYLAP             DATE,  
    LOIDAN              NVARCHAR2(100),
    CANNANG             NUMBER,
    CHIEUCAO            NUMBER,
    HUYETAPTAMTHU       NUMBER,
    HUYETAPTAMTRUONG    NUMBER,
    
    CONSTRAINT P_PHIEUKHAM PRIMARY KEY (MAPHIEUKHAM),
    CONSTRAINT F_PK_PDK FOREIGN KEY (MAPHIEUDANGKY) REFERENCES PHIEUDANGKY(MAPHIEUDANGKY)
);

CREATE TABLE BENH(
    MABENH      VARCHAR2(10) NOT NULL,
    TENBENH     NVARCHAR2(50),
    
    CONSTRAINT P_BENH PRIMARY KEY (MABENH)
);

CREATE TABLE CHITIETCHANDOAN(
    MAPHIEUKHAM     VARCHAR2(10) NOT NULL,
    MABENH          VARCHAR2(10) NOT NULL,
    
    CONSTRAINT P_CHITIETCHANDOAN PRIMARY KEY (MAPHIEUKHAM, MABENH),
    CONSTRAINT F_CTCD_PK FOREIGN KEY (MAPHIEUKHAM) REFERENCES PHIEUKHAM(MAPHIEUKHAM),
    CONSTRAINT F_CTCD_B FOREIGN KEY (MABENH) REFERENCES BENH(MABENH)
);

CREATE TABLE TOATHUOC(
    MATOATHUOC          VARCHAR2(10) NOT NULL,
    MAPHIEUKHAM         VARCHAR2(10),
    TONGTIEN            NUMBER,
    TRANGTHAITHANHTOAN  NVARCHAR2(20),
    
    CONSTRAINT P_TOATHUOC PRIMARY KEY (MATOATHUOC),
    CONSTRAINT F_TT_PK FOREIGN KEY (MAPHIEUKHAM) REFERENCES PHIEUKHAM(MAPHIEUKHAM)
);

CREATE TABLE THUOC(
    MATHUOC         VARCHAR2(10) NOT NULL,
    TENTHUOC        NVARCHAR2(50),
    QCDONGGOI       NVARCHAR2(30),
    DONVITINH       NVARCHAR2(10),
    DONGIA          NUMBER,
    TONKHO          NUMBER,
    
    CONSTRAINT P_THUOC PRIMARY KEY (MATHUOC)
);

CREATE TABLE CHITIETTOATHUOC(
    MATOATHUOC      VARCHAR2(10) NOT NULL,
    MATHUOC         VARCHAR2(10) NOT NULL,
    DONGIA          NUMBER,
    SOLUONG         NUMBER,
    GHICHU          NVARCHAR2(50),
    
    CONSTRAINT P_CHITIETTOATHUOC PRIMARY KEY (MATOATHUOC, MATHUOC),
    CONSTRAINT F_CTTT_TT FOREIGN KEY (MATOATHUOC) REFERENCES TOATHUOC(MATOATHUOC),
    CONSTRAINT F_CTTT_T FOREIGN KEY (MATHUOC) REFERENCES THUOC(MATHUOC)
);
